name: CI - API BreastCancer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        if [ -f test_api.py ]; then pytest -v; else echo "No test file found"; fi

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t breastcancer-api -f Dockerfile.txt .

    # Descomentar si quieres subir a DockerHub/GHCR
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Push Docker image
    #   run: |
    #     docker tag breastcancer-api your-dockerhub-username/breastcancer-api:latest
    #     docker push your-dockerhub-username/breastcancer-api:latest
